WaypointController:
  ros__parameters:
    waypoints:
      - frame_id: "map"
        pose:
          position:
            x: -2.0
            y: -2.0
            z: 0.0
      - frame_id: "map"
        pose:
          position:
            x: 1.0
            y: -3.0
            z: 0.0
      - frame_id: "map"
        pose:
          position:
            x: 2.0
            y: 3.0
            z: 0.0
      - frame_id: "map"
        pose:
          position:
            x: 0.0
            y: 5.0
            z: 0.0
      - frame_id: "map"
        pose:
          position:
            x: -3.0
            y: 4.0
            z: 0.0
      - frame_id: "map"
        pose:
          position:
            x: -6.0
            y: -3.0
            z: 0.0
